### ISSUE TITLE
remove binaries from repository

### ISSUE THREAD

**Issue by barryrowlingson** [sassalley/hexmapr#1]
The `src` directory has some binaries (.so and .o) which you should probably delete. I suspect they may be messing up my install:

```
 unable to load shared object `/library/hexmapr/libs/hexmapr.so':
  /library/hexmapr/libs/hexmapr.so: invalid ELF header
```

Add them to your .gitignore

**Comment by sassalley** [comment]
Apologies for this - still learning. I believe that commit `3e18de7` should have achieved this. Please let me know if the issue persists.
