### ISSUE TITLE
polygons too few

### ISSUE THREAD

**Issue by wegmann** [sassalley/hexmapr#10]
Hello,

how do I change the command if I get that I have too few (small) polygons? thanks, Martin

for (i in 1:6){
+   new_cells <-  calculate_cell_size(original_shapes, original_details,0.05, 'hexagonal', i)
+   plot(new_cells[[2]], main = paste("Seed",i, sep=" "))
+ }
[1] 2
[1] 197.2832
[1] "too few polygons"
[1] 1
[1] 197.0859
[1] "too few polygons"
 Show Traceback
 
 Rerun with Debug
 Error in .local(x, n, type, ...) : 
  iteration did not converge; try enlarging argument iter

**Comment by sassalley** [comment]
Hi Martin, 
 
A couple of things just to help me troubleshoot

1. Do you know how many separate polygons your input file has?
2. Could you share it?
3. Have other learning rates worked for you (e.g. 0.03) 

Best

@sassalley

**Comment by sassalley** [comment]
Closing this for now as commit `dff0ef2` should have helped. Please re-open if not.
