### ISSUE TITLE
Get path to test data using system.file

### ISSUE THREAD

**Issue by barryrowlingson** [sassalley/hexmapr#2]
Not sure what the `rep` is doing here:

```
#In the working directory of the package.
input_file <- rep("inst/extdata/london_LA.json")
```

but:

```
input_file = system.file("inst/extdata/london_LA.json",package="hexmapr")
```

will remove the "In the working directory of the package" requirement and work anywhere.

**Comment by sassalley** [comment]
Thanks for the suggestions. The `rep` was a hangover from previous code and should have been removed. The new version uses `system.file` as per your suggestion.
