### ISSUE TITLE
create maps from sf object

### ISSUE THREAD

**Issue by pssguy** [sassalley/hexmapr#8]
Is it possible - or could you enhance package so -  that the hex and regular maps can be created from the starting point of a data.frame with a simple feature geometry list-column

**Comment by sassalley** [comment]
It is something that I have thought about. I do believe that it would be a good idea given that `sf` is a potential replace meant for `sp`. I rely a lot on a couple of functions from `sp` which are designed for `sp` types but will look into it.

**Comment by pssguy** [comment]
I've been trying - so far without success - to create a SpatialPolygonsDataFrame  from an sf. Then I can just apply your functions. I'm pretty sure it can be done but am new to this area so haven't achieved as yet

If you just had a function that could do that then that would solve my issue
However, longer term, sf, as default, is probably the way to go 

BTW congrats on a great package 100*'s and counting

**Comment by sassalley** [comment]
@pssguy any luck with the conversion? If i were to implement an SF option i'd probably just incorporate `as(nc, 'Spatial')` or the approaches discussed [here](https://gis.stackexchange.com/questions/239118/r-convert-sf-object-back-to-spatialpolygonsdataframe) which I don't think would help with your issue?

**Comment by pssguy** [comment]
@sassalley 
Yes, I think `as(nc, 'Spatial')` does the trick. Thanks
